### ISSUE TITLE
Read Carriersettings and export Carriersettings

### ISSUE THREAD

**Issue by lynxis** [omnt/OpenMobileNetworkToolkit#2]
It looks even for foreign Subscribers you can read out the carrier settings.
If this is really possible, 
it would be great to export and import carrier settings. Either simple by .csv/xml files. (Or any other simple file format).

**Comment by PeterHasse** [comment]
i will look into this, sadly carrier settings are implemented via a strange class called perssistant bundle which is terrible to handle / parse.

**Comment by hajoha** [comment]
Done with [Release 0.4](https://github.com/omnt/OpenMobileNetworkToolkit/releases/tag/0.4).
