### ISSUE TITLE
iPerf Upload with 0 Duration

### ISSUE THREAD

**Issue by nickvsnetworking** [omnt/OpenMobileNetworkToolkit#27]
### Description
Currently when creating an iPerf test you can set the duration of the test, or set to 0 which will run forever / continuous. 
This works fine.
But it seems the data is only uploaded / pushed to InfluxDB on completion of the test, so running a continuous test will never actually yield the results to get pushed.

### How to Reproduce
1. Go to iPerf
2. Start a job with the duration set to 0
3. "Send"
4. Check output to InfluxDB (Nothing is pushed)

### Possible Fix
I'm not sure if it's possible to upload the results as each datapoint comes back from iPerf, or if the process needs to wait until the job has completed before getting access to the results.

Perhaps a simple "Run continuously" toggle when sending the iPerf job like for Ping, that will restart the job after it completes, so each iPerf instance runs for a period of time, but then starts again after it's returned?

**Comment by hajoha** [comment]
Hi Nick,

Thank you for informing us. I'm not entirely sure this is a bug, as we're using the [Worker API](https://developer.android.com/develop/background-work/background-tasks/persistent/how-to/chain-work).

We have three Workers:
 
1. `Iperf3Worker`
2. `Iperf3ToLineProtocolWorker`
3. `Iperf3UploadWorker`

These workers are chained [together](https://github.com/omnt/OpenMobileNetworkToolkit/blob/main/app/src/main/java/de/fraunhofer/fokus/OpenMobileNetworkToolkit/Iperf3/Iperf3Fragment.java#L503):
```
iperf3WM.beginWith(iperf3WR).then(iperf3LP).then(iperf3UP).enqueue();
```
If the `Iperf3Worker` never stops running, the other two will not be called. For our current use case, it doesn't make sense to upload iPerf3 data while running an iPerf3 test. 

However, I share your frustration with the current setup. In the future, it would be ideal to configure multiple iPerf3 tests (running either in parallel or sequentially) and allow them to run continuously.

A potential solution for now could be to [stop](https://github.com/omnt/OpenMobileNetworkToolkit/blob/main/docs/iperf3.md#stop-iperf3-run) the iPerf3 run and [upload](https://github.com/omnt/OpenMobileNetworkToolkit/blob/main/docs/iperf3.md#upload-to-remote-influxdb) the data via the GUI. I'm currently unable to test this myself, so please let me know if it works.

**Comment by hajoha** [comment]
I tested it with the latest [release 0.4](https://github.com/omnt/OpenMobileNetworkToolkit/releases/tag/0.4), and it's now working as described in my previous comment.
