### ISSUE TITLE
Discrepancy between RSSNR values in DataProvider.getCellInformation() and DataProvider.getSignalStrengthInformation()

### ISSUE THREAD

**Issue by RkShaRkz** [omnt/OpenMobileNetworkToolkit#40]
### Context
- **Device:**
- **Carrier Privileges (Y/N):**
- **Android Version:**
- **App Version:**
- **Git Hash:**

### Description
While we're trying to get a constant (consistent?) measurement of the RSSNR parameter, we've noticed a discrepancy between the value in both the "Details" tab, and what is programatically returned as well. It may also be device/vendor specific, since I'm not seeing it on my test device but am clearly seeing it on my colleagues' devices.

### How to Reproduce
While unclear, it falls down to something like this. Steps to reproduce the behavior:
1. Go to Details panel
2. Check RSSNR in both Cell Information and Signal Strength cards
3. Depending on the device/vendor, they will either be the same, or the "Cell information" one will show `null` (or "N/A") while the "Signal Strength" one will show an actual number, e.g. -1

### Expected Behavior
I'd expect both the registered CellInformation obtained by `DataProvider.getCellInformation()` and the `DataProvider.getSignalStrengthInformation()` to return the same value

### Actual Behavior
Depending on the device, they do not always return the same value; while the one from Signal Strength always seems to have a RSSNR, the Cell Information card doesn't.

### Screenshots

# quick panel
![image](https://github.com/user-attachments/assets/7f3459b3-44cd-4c28-9956-5c8bb0ad058b)

# details panel
![image](https://github.com/user-attachments/assets/448ac98d-56e4-4703-982a-820cf059e0ec)

### Additional Context
This is better explained with code.

```
    private static NetworkDataModel getCloudCityData() {
        List<CellInformation> cellsInfo = dp.getCellInformation();
        List<CellInformation> signalInfo = dp.getSignalStrengthInformation();
        LocationInformation location = dp.getLocation();

        CellInformation currentCell = findRegisteredCell(cellsInfo);
        CellInformation currentSignal = null;
        // After testing on a real phone, apparently there's only one SignalStrengthInformation
        // CellInformation member in the list, so lets just take the first one if it's there
        if (!signalInfo.isEmpty()) {
            currentSignal = signalInfo.get(0);
        }

        String category = currentCell.getCellType().toString();

        NetworkDataModel dataModel = new NetworkDataModel();

        dataModel.setCategory(currentCell.getCellType().toString());
        dataModel.setLatitude(location.getLatitude());
        dataModel.setLongitude(location.getLongitude());
        dataModel.setAccuracy(location.getAccuracy());
        /* Convert to km/h */
        dataModel.setSpeed(location.getSpeed() * 3.6);

        dataModel.setCellData(getCellInfoModel(category, currentCell));
        
        // Lets initialize our MeasurementModel for sending from the registered cell model, then overwrite it's values
        // with what we found in the SignalInformation
        MeasurementsModel modelForSending = getMeasurementsModel(category, currentCell);
        updateMeasurementModelByCell(modelForSending, currentSignal);

        Log.d("currentCellMeasurements: "+currentCell);
        Log.d("signalStrengthMeasurements: "+currentSignal);
        Log.d("modelForSending: "+modelForSending);

        dataModel.setValues(modelForSending);

        return dataModel;
    }

    public static CellInformation findRegisteredCell(@NonNull List<CellInformation> cellList) {
        CellInformation retVal = null;

        for (CellInformation ci: cellList) {
            if (!ci.isRegistered()) {
                continue;
            }

            retVal = ci;
        }

        return retVal;
    }
```

And the logs will print out this:
```
currentCellMeasurements: MeasurementsModel{rsrp=-94, rsrq=-14, rssnr=null, csirsrp=null, csirsrq=null, csisinr=null, ssrsrp=null, ssrsrq=null, sssinr=null, dummy=null}

signalStrengthMeasurements: MeasurementsModel{rsrp=-98, rsrq=-15, rssnr=-1, csirsrp=null, csirsrq=null, csisinr=null, ssrsrp=null, ssrsrq=null, sssinr=null, dummy=null}

modelForSending: MeasurementsModel{rsrp=-98, rsrq=-15, rssnr=-1, csirsrp=null, csirsrq=null, csisinr=null, ssrsrp=null, ssrsrq=null, sssinr=null, dummy=null}
```

I'm also wondering why the `CellInformation` returned by `DataProvider.getSignalStrengthInformation()` isn't registered, but since it only had one entry in the list i just took that.

### Possible Fix

no idea for a fix, but my workaround can also be seen in the posted code above.

**Comment by RkShaRkz** [comment]
While at it, I've noticed only `LTEInformation` has RSSNR, so I'm wondering whether this parameter is applicable to all possible networks (3G / 4G / 5G) since they're not all LTE networks? can this particular approach be used to verify the RSSNR of a 5g network?

**Comment by hajoha** [comment]
Hi @RkShaRkz, Android provides two APIs for querying signal data:

1. [onSignalStrengthsChanged](https://developer.android.com/reference/android/telephony/TelephonyCallback.SignalStrengthsListener#onSignalStrengthsChanged(android.telephony.SignalStrength))
2. [onCellInfoChanged](https://developer.android.com/reference/android/telephony/TelephonyCallback.CellInfoListener#onCellInfoChanged(java.util.List%3Candroid.telephony.CellInfo%3E))

We've observed that the second callback, `onCellInfoChanged`, updates more frequently. However, we’re not sure why there are differences in the values returned by each API. Additionally, both callbacks lack CSI-RSRP, CSI-RSRQ, and CSI-SINR for 5G NR SA cells.

We log data from both APIs to InfluxDB using either SignalStrength or CellInformation. If you're using our [Dashboards](https://github.com/omnt/Dashboards), you can choose to display either CellInformation or SignalStrength.

![image](https://github.com/user-attachments/assets/8721bab2-fc43-4534-a585-9d18154fa408)




> Can this approach be used to verify the RSSNR of a 5G network?

No, RSSNR is not part of 5G, at least not for 5G SA (Standalone). In 5G SA, you should expect to see SS-RSRP, SS-RSRQ and SS-SINR instead. You can read more about this [here](https://developer.android.com/reference/android/telephony/CellSignalStrengthNr) or in the 3GPP specifications.

We have implemented logging for various [cellular network standards](https://github.com/omnt/OpenMobileNetworkToolkit/tree/main/app/src/main/java/de/fraunhofer/fokus/OpenMobileNetworkToolkit/DataProvider/CellInformations).
