### ISSUE TITLE
With SDK35 compiled current GitHub-version crashes immediately at startup (Android14, Pixel7)

### ISSUE THREAD

**Issue by Nazdravi** [omnt/OpenMobileNetworkToolkit#5]
Hi,
compiled the app from the github sources. This did succeed with Android-SDK35, but App crashes immediately in startup.

Kind regards
Arndt

PS: letzte Woche Mittwoch konnte ich nicht danach fragen, weil ich es zu dem Zeitpunkt noch nicht probiert hatte

**Comment by PeterHasse** [comment]
Helo Arndt

i dont see the missing value in the log but it might be one if the issues we fixed this week.
Please try again after https://github.com/omnt/OpenMobileNetworkToolkit/pull/6 is merged.

also you might want to delete the log, it contains log not related to OMNT with private data of yours
