### ISSUE TITLE
Example Grafana Dashboards?

### ISSUE THREAD

**Issue by nickvsnetworking** [omnt/OpenMobileNetworkToolkit#8]
G'day folks,
Saw the talk at Open Source Mobile Network Technologies Conference and really keen to play with this.
I saw the demo Grafana dashboards you showed, are these available publicly anywhere?
Cheers,
Nick

**Comment by hajoha** [comment]
Hi Nick,

sorry for the late response. Yes I just [pushed](https://github.com/omnt/Dashboards) them. We'd love to hear your thoughts!

Cheers
Johann
